apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./k8s_config/*
build:
  local:
    push: false
  artifacts:
    - image: halbard/auth
      context: auth
      docker:
        dockerfile: Dockerfile
